### ISSUE TITLE
taShowHtml

### ISSUE THREAD

**Issue by varkadov** [textAngular/textAngular#1132]
When set ta-show-html with some controller field in link function when $eval I get undefined not field value.
How to fix this?

**Comment by pbassut** [comment]
You don't need to ```$eval``` the attribute passed to ta-show-html because it's already evaluated by textAngular.

**Comment by arkasha69** [comment]
There is example http://plnkr.co/edit/mOpQGrB8rxFOyuDgRNeP?p=preview - when is pass into ta-show-html variable showHtml html mode don't turn on, if I pass true - it's ok

**Comment by pbassut** [comment]
Right.
Looks like taShowHtml is not taking into consideration the scope of the controller. That's why you can only pass things that won't take the scope into consideration. Like ```true``` or ```false``` or when in a ngRepeat loop: ```$index == 0```.
Since this is the intended behaviour, I'll mark it as an enhancement. It's a very easy fix, though.
